Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),

]

blog/models.py
from django.db import models


# Create your models here.


class Article(models.Model):
    title = models.TextField()
    content = models.TextField()


class FriendLink(models.Model):
    link = models.TextField()


class Message(models.Model):
    author = models.TextField()
    content = models.TextField()


class ArticleComment(models.Model):
    author = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.TextField()


class PhotoComment(models.Model):
    author = models.TextField()
    photo_name = models.TextField()
    content = models.TextField()

templates/article.html
{% extends 'blog_base.html' %}

{% block title %}
    文章列表
{% endblock %}

{% block body %}

    {% for article in article_list %}
        <a href="{% url 'article_detail' article.id %}">
            {{ article.title }}
        </a>
        <br>
    {% endfor %}



{% endblock %}

templates/article_detail.html
{% extends 'blog_base.html' %}

{% block title %}
    文章
{% endblock %}

{% block body %}

    {#    <input type="text" name="title" value="{{ article.title }}">#}
    {#    <br>#}
    {#    <textarea type="text" name="content">#}
    {#    {{ article.content }}#}
    {#    </textarea>#}
    <p>{{ article.title }}</p>
    <p> {{ article.content }}  </p>

    <form action="{% url 'add_comment' article.id %}" method="post">
        {% csrf_token %}
        添加评论<input type="text" name="content">
        <br>
        昵称<input type="text" name="author">
        <input type="submit" value="提交">
    </form>

    {% for comment in article.articlecomment_set.all %}
        <p>
            {{ comment.author }}
            <br>
            {{ comment.content }}
        </p>
        <br>
    {% endfor %}




{% endblock %}

templates/article_management.html
{% extends 'management_base.html' %}

{% block title %}
博客后台
{% endblock %}


{% block body %}

    <h6>
        <a href="{% url 'write_article' %}">
           写文章
        </a>
    </h6>

    {% for article in article_list %}
        {{ article.title }}
        <a href="{% url 'article_delete' article.id %}">
        删除
        </a>

        <br>

    {% endfor %}


{% endblock %}

templates/blog_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}

    {% endblock %}</title>
    {% load staticfiles %}

    <link rel="stylesheet" href="../static/Bootstrap/css/bootstrap.css">
    <script src="../static/Bootstrap/js/bootstrap.js"></script>
</head>
<body>


<div class="container">
    <h1>
        <a href="{% url 'index' %}">
            博客
        </a>


    </h1>
    {% if request.user.is_authenticated %}
        <a href="{% url 'log_out' %}">
            登出
        </a>
    {% else %}
        <a href="{% url 'log_in' %}">
            登录
        </a>
    {% endif %}



    <div class="row">

        <div class="col-sm-3">
            <a href="{% url 'article' %}">文章</a>
        </div>
        <div class="col-sm-3">
            <a href="{% url 'show_photos' %}">图片</a>
        </div>
        <div class="col-sm-3">
            <a href="{% url 'messages' %}">留言</a>
        </div>
        <div class="col-sm-3">
            <a href="{% url 'friend_links' %}">友情链接</a>
        </div>
    </div>

    <div class="row">
        <a href="{% url 'personal_info' %}">
            个人信息
        </a>
    </div>

    {% block body %}

    {% endblock %}


</div>


</body>
</html>

templates/blog_index.html
{% extends 'blog_base.html' %}


{% block title %}
    博客
{% endblock %}

templates/friend_link_management.html
{% extends 'management_base.html' %}

{% block title %}
    友情链接管理
{% endblock %}

{% block body %}

    {#    <h6>#}
    {#        <a href="{% url 'add_friend_link' %}">#}
    {#            添加友情链接#}
    {#        </a>#}
    {#    </h6>#}

    <form action="{% url 'add_friend_link' %}" method="post">
        {% csrf_token %}
        添加友情链接: <input type="text" name="friend_link">
        <br>

        <input type="submit" value="提交">
    </form>

    {% for friend_link in friend_link_list %}
        {{ friend_link.link }}
        <a href="{% url 'friend_link_delete' friend_link.id %}">
            删除
        </a>

        <br>

    {% endfor %}

{% endblock %}

templates/log_in.html
{% extends 'blog_base.html' %}

{% block title %}
    登录
{% endblock %}

{% block body %}
    <form action="{% url 'log_in' %}" method="post">
        {% csrf_token %}
        用户名<input type="text" name="username">
        <br>
        密码<input type="text" name="password">
        <input type="submit" value="提交">
    </form>


{% endblock %}

templates/management_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}

    {% endblock %}</title>
    {% load staticfiles %}

    <link rel="stylesheet" href="../static/Bootstrap/css/bootstrap.css">
    <script src="../static/Bootstrap/js/bootstrap.js"></script>
</head>
<body>


<div class="container">
    <h1>
        <a href="{% url 'blog_backend' %}">
            博客后台
        </a>
    </h1>
    {% if request.user.is_authenticated %}

        <a href="{% url 'log_out' %}">
            登出
        </a>
    {% else %}
        <a href="{% url 'log_in' %}">
            登录
        </a>
    {% endif %}

    <div class="row">

        <div class="col-sm-3">
            <a href="{% url 'article_management' %}">文章管理</a>
        </div>
        <div class="col-sm-3">
            <a href="{% url 'upload_photo' %}">照片管理</a>
        </div>
        <div class="col-sm-3">
            <a href="{% url 'message_management' %}">留言管理</a>
        </div>
        <div class="col-sm-3">
            <a href="{% url 'friend_link_management' %}">友情链接管理</a>
        </div>
    </div>

    <div class="row">
        <a href="{% url 'personal_info_management' %}">
            个人信息管理
        </a>
    </div>

    {% block body %}

    {% endblock %}


</div>


</body>
</html>

templates/messages.html
{% extends 'blog_base.html' %}

{% block title %}
    留言
{% endblock %}

{% block body %}

    {% for message in message_list %}
        {{ message.author }}:{{ message.content }}

        <br>
    {% endfor %}

    <form action="{% url 'add_message' %}" method="post">
        {% csrf_token %}
        添加留言<input type="text" name="content">
        <br>
        昵称<input type="text" name="author">
        <input type="submit" value="提交">
    </form>

{% endblock %}

templates/personal_info.html
{% extends 'blog_base.html' %}

{% block title %}
    个人信息
{% endblock %}

{% block body %}
    姓名：{{ name }}
    <br>
    性别：{{ gender }}
    <br>
    年龄：{{ age }}
    <br>
    学校：{{ school }}
    <br>
{% endblock %}

templates/personal_info_management.html
{% extends 'management_base.html' %}

{% block title %}
    个人信息管理
{% endblock %}

{% block body %}
    <form action="{% url 'personal_info_management' %}" method="post">
        {% csrf_token %}
        姓名：<input type="text" name="name" value="{{ name }}">
        年龄：<input type="text" name="age" value="{{ age }}">
        性别：<input type="text" name="gender" value="{{ gender }}">
        学校：<input type="text" name="school" value="{{ school }}">
        <input type="submit" value="提交">
    </form>
{% endblock %}

templates/photo_detail.html
{% extends 'blog_base.html' %}

{% block title %}
    图片
{% endblock %}

{% block body %}
    <img src="../static/photos/{{ photo_name }}" alt="">
    <br>
    <form action="{% url 'add_photo_comment' photo_name %}" method="post">
        {% csrf_token %}
        作者 <input type="text" name="author">
        <br>
      评论内容  <input type="text" name="content">
        <br>
        <input type="Submit" value="提交">
    </form>
    <br>
    {% for photo_comment in photo_comment_list %}
     作者　　   {{ photo_comment.author }}
        　　<br>
      评论内容  {{ photo_comment.content }}
        <br>
    {% endfor %}


{% endblock %}

templates/photos.html
{% extends 'blog_base.html' %}

{% block title %}
    图片
{% endblock %}

{% block body %}

    {% for photo_name in photo_name_list %}
        <a href="{% url 'photo_detail' photo_name %}">
            <img src="../static/photos/{{ photo_name }}" alt="">
        </a>


    {% endfor %}


{% endblock %}

templates/write_article.html
{% extends 'management_base.html' %}

{% block title %}
写文章
{% endblock %}

{% block body %}
    <form action="{% url 'write_article' %}" method="post">
        {% csrf_token %}
        title: <input type="text" name="title">
        <br>
        content:  <textarea type="text" name="content"> </textarea>
        <br>
        <input type="submit" value="提交">
    </form>


{% endblock %}